#!/usr/bin/env bash
## Screenshot script for Archcraft - Updated by Leoberbert 💪
## Based on original by Aditya Shakya <adi1090x@gmail.com>
# File details
time=$(date +%Y-%m-%d-%H-%M-%S)
geometry=$(xrandr | grep 'current' | head -n1 | cut -d',' -f2 | tr -d '[:blank:],current')
# Determine screenshot directory with fallback
xdg_output="$(command -v xdg-user-dir &>/dev/null && xdg-user-dir PICTURES)"
pictures_dir="${xdg_output:-$HOME/Pictures}"
dir="${pictures_dir}/Screenshots"
file="Screenshot_${time}_${geometry}.png"
border='0.322,0.585,0.886'
# Ensure directory exists
mkdir -p "$dir"
# Notify and view screenshot
notify_view () {
	notify_cmd_shot='dunstify -u low -h string:x-dunst-stack-tag:obscreenshot -i /usr/share/archcraft/icons/dunst/picture.png'
	$notify_cmd_shot "Copied to clipboard."
	paplay /usr/share/sounds/freedesktop/stereo/screen-capture.oga &>/dev/null &
	viewnior "${dir}/${file}"
	if [[ -e "${dir}/${file}" ]]; then
		$notify_cmd_shot "Screenshot Saved."
	else
		$notify_cmd_shot "Screenshot Deleted."
	fi
}
# Copy screenshot to clipboard
copy_shot () {
	tee "${dir}/${file}" | xclip -selection clipboard -t image/png
}
# Countdown
countdown () {
	for sec in $(seq $1 -1 1); do
		dunstify -t 1000 -h string:x-dunst-stack-tag:screenshottimer -i /usr/share/archcraft/icons/dunst/timer.png "Taking shot in : $sec"
		sleep 1
	done
}
# Take shots
shotnow () {
	cd "$dir" && maim -u -f png | copy_shot
	notify_view
}
shot5 () {
	countdown '5'
	sleep 1 && cd "$dir" && maim -u -f png | copy_shot
	notify_view
}
shot10 () {
	countdown '10'
	sleep 1 && cd "$dir" && maim -u -f png | copy_shot
	notify_view
}
shotwin () {
	cd "$dir" && maim -u -f png -i "$(xdotool getactivewindow)" | copy_shot
	notify_view
}
shotarea () {
	cd "$dir" && maim -u -f png -s -b 2 -c "${border},0.25" -l | copy_shot
	notify_view
}
# Execute
case "$1" in
	--now)  shotnow ;;
	--in5)  shot5 ;;
	--in10) shot10 ;;
	--win)  shotwin ;;
	--area) shotarea ;;
	*)
		echo -e "Available Options: --now --in5 --in10 --win --area"
		;;
esac
exit 0